language: erlang
addons:
    apt:
      packages:
      - sqlite3
install:
    - epmd -daemon
otp_release:
    - 22.2
    - 23.0
# blocklist
branches:
    except:
    - master
# AR UT
script:
    - ./bin/test
